name:                unicode-transforms
version:             0.3.3
synopsis:            Unicode normalization
description:         Fast Unicode 9.0 normalization in Haskell (NFC, NFKC, NFD, NFKD).
homepage:            http://github.com/harendra-kumar/unicode-transforms
license:             BSD3
license-file:        LICENSE
author:              Harendra Kumar
maintainer:          harendra.kumar@gmail.com
copyright:
  - 2016-2017 Harendra Kumar
  - 2014–2015 Antonio Nikishaev
category:            Data,Text,Unicode
stability:           Experimental
github:              harendra-kumar/unicode-transforms

tested-with: GHC==7.10.3, GHC==8.0.2, GHC==8.2.2

extra-source-files:
  - Changelog.md
  - NOTES.md
  - README.md
  - benchmark/data/*.txt
  - stack.yaml
  - stack-7.10.yaml
  - unicode-data/README.md
  - unicode-data/ucd/NormalizationTest.txt
  - unicode-data/extra/NormalizationTest.txt
  - unicode-data/stack.yaml
  - unicode-data/ucd2haskell.cabal
  - unicode-data/UCD2Haskell.hs

flags:
  has-llvm:
    description: Use llvm backend (faster) for compilation
    default: False
    manual: True
  has-icu:
    description: Use text-icu for benchmark and test comparisons
    default: False
    manual: True
  dev:
    description: Developer build
    default: False
    manual: True

ghc-options:
  - -Wall
  - -fwarn-identities
  - -fwarn-incomplete-record-updates
  - -fwarn-incomplete-uni-patterns
  - -fwarn-tabs

when:
  - condition: flag(dev)
    then:
      ghc-options: -O0
    else:
      ghc-options: -O2 -funbox-strict-fields
  - condition: flag(has-llvm)
    ghc-options: -fllvm

dependencies: base >= 4.7 && < 5

library:
  source-dirs: .
  exposed-modules:
    - Data.ByteString.UTF8.Normalize
    - Data.Text.Normalize
    - Data.Unicode.Types
  other-modules:
    - Data.Unicode.Internal.NormalizeStream
    - Data.Unicode.Properties.BitArray
    - Data.Unicode.Properties.CombiningClass
    - Data.Unicode.Properties.Compositions
    - Data.Unicode.Properties.Decomposable
    - Data.Unicode.Properties.DecomposableK
    - Data.Unicode.Properties.Decompose
    - Data.Unicode.Properties.DecomposeHangul
    - Data.Unicode.Properties.Decompositions
    - Data.Unicode.Properties.DecompositionsK
    - Data.Unicode.Properties.DecompositionsK2
  dependencies:
    - bitarray   >= 0.0.1 && < 0.1
    - bytestring >= 0.9   && < 0.11
    - text       >= 1.1.1 && < 1.3

# developer mode only
# Simple program to generate perf stats
#executables:
#  normalizefile:
#    source-dirs: benchmark
#    main:        NormalizeFile.hs
#    other-modules: []
#    dependencies:
#      - deepseq >= 1.1.0.0
#      - filepath
#      - path
#      - path-io
#      - text
#      - unicode-transforms

tests:
  ucd:
    source-dirs: test
    main:        NormalizationTest.hs
    other-modules: []
    dependencies:
      - getopt-generics    >= 0.11  && < 0.14
      - split              >= 0.1   && < 0.3
      - text               >= 1.1.1 && < 1.3
      - unicode-transforms
  quickcheck:
    source-dirs: test
    main:        Properties.hs
    other-modules: QuickCheckUtils
    dependencies:
      - deepseq     >= 1.1 && < 1.5
      - QuickCheck  >= 2.1 && < 2.12
      - text        >= 1.1.1 && < 1.3
      - unicode-transforms
    when:
      - condition: flag(has-icu)
        cpp-options: -DHAS_ICU
        dependencies:
          - text-icu >= 0.6.2.1
  extras:
    source-dirs: test
    main:        Extra.hs
    other-modules: QuickCheckUtils
    dependencies:
      - deepseq     >= 1.1 && < 1.5
      - QuickCheck  >= 2.1 && < 2.12
      - text        >= 1.1.1 && < 1.3
      - unicode-transforms

benchmarks:
  bench:
    when:
      - condition: flag(has-icu)
        cpp-options: -DBENCH_ICU
        dependencies:
          - text-icu >= 0.6.2.1 && < 0.8
      - condition: impl(ghc < 7.10)
        dependencies:
          - path (< 0.5.12 || > 0.5.12)

    source-dirs: benchmark
    main:        Benchmark.hs
    other-modules: []

    dependencies:
      - gauge                >= 0.2.0 && < 0.3
      - deepseq              >= 1.1.0 && < 1.5
      - filepath             >= 1.0   && < 2
      - optparse-applicative >= 0.0.1 && < 0.15
      - path                 >= 0.0.0 && < 0.7
      - path-io              >= 0.1.0 && < 1.4
      - text                 >= 1.1.1 && < 1.3
      - unicode-transforms
