packages:
- '.'
resolver: lts-18.18
extra-deps:
# [TODO] re-enable once unicode-data is released with quick check
# - unicode-data-XXX
- git: https://github.com/composewell/unicode-data.git
  commit: dffcca331e4c8479c75983cfc8ce2591e9bad601
  subdirs:
    - unicode-data
- tasty-bench-0.3

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
